version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: sharp
    versions:
    - 0.28.0
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
  - dependency-name: release-it
    versions:
    - 14.5.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.7.1
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-template-lint
    versions:
    - 3.1.1
  - dependency-name: "@ember/test-helpers"
    versions:
    - 2.2.1
  commit-message:
    prefix: ""
  registries:
  - npm-registry-npm-pkg-github-com
